config/routes.rb
Rails.application.routes.draw do
  # get 'static_pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_for :users, controllers: { registrations: 'users/registrations'}

  resources :disciplines do
    resources :materials, only: [:new, :create, :index, :show] do
      member do
        patch 'update_access', to: 'materials#update_access', as: :update_access
      end
    end  
    member do
      delete 'detach_material/:material_id', to: 'disciplines#detach_material', as: :detach_material
    end
  end
  resources :schedules do
    get 'load_disciplines', on: :collection
    get 'carousel', on: :member
  end
  resources :users, only: [:edit, :update, :show]
  get 'search_users', to: 'users#search_users'
  get 'search_users_list', to: 'users#search_users_list'
  
  resources :groups
  resources :courses do
    member do
      get 'teachers' => 'courses#edit_teachers'
      patch 'teachers' => 'courses#update_teachers'
      get 'students' => 'courses#edit_students'
      patch 'students' => 'courses#update_students'
    end
  end

  namespace :moderator do
    resources :courses do
      member do
        get 'teachers' => 'courses#edit_teachers'
        patch 'teachers' => 'courses#update_teachers'
        get 'students' => 'courses#edit_students'
        patch 'students' => 'courses#update_students'
        get 'disciplines' => 'courses#edit_disciplines'
        patch 'disciplines' => 'courses#update_disciplines'
      end
    end
    resources :disciplines do
      resources :materials, only: [:new, :create, :show, :index] do
        member do
          patch 'update_access', to: 'materials#update_access', as: :update_access
        end
      end  
      member do
        delete 'detach_material/:material_id', to: 'disciplines#detach_material', as: :detach_material
        post 'update_order', to: 'disciplines#update_order', as: :update_order
      end
    end
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update] do
      # member do
      #   patch 'toggle_block' => 'users#toggle_block'
      # end
    end
    root "users#index"
    resources :roles
    resources :groups do
      # member do
      #   get 'search_users' => 'groups#search_users'
      #   
      # end
    end
  end

  resources :chats
  resources :messages, only: [:create]

  root "static_pages#home"
end

app/models/discipline.rb
class Discipline < ApplicationRecord
    has_and_belongs_to_many :role_users
    has_many :materials
    has_many :course_disciplines
    has_many :courses, through: :course_disciplines
    
    validates :name, presence: true, uniqueness: true
end

app/controllers/disciplines_controller.rb
# controllers/disciplines_controller.rb
class DisciplinesController < ApplicationController
    before_action :set_discipline, only: [:show, :edit, :update, :destroy]
    respond_to :js, only: [:create]
  
    def index
      @disciplines = Discipline.all
    end
  
    def new
      @discipline = Discipline.new
      @material = Material.new
    end
  
    def create
      @discipline = Discipline.new(discipline_params)
      if @discipline.save
        moderator = current_user.get_role_user('moderator')
        if !moderator.nil?
          @discipline.role_users << moderator
        end
        redirect_to disciplines_path, notice: 'Дисциплина успешно создана!'
      else
        @available_materials = Material.all
        redirect_to request.referer, alert: "Имя должно быть уникальным"
      end
    end
  
    def show
      @materials = @discipline.materials
    end
  
    def edit
      @discipline = Discipline.find(params[:id])
      @materials = @discipline.materials
    end
  
    def update
      if @discipline.update(discipline_params)
        redirect_to @discipline, notice: 'Дисциплина успешно обновлена!'
      else
        @available_materials = Material.all
        redirect_to request.referer, alert: "Имя должно быть уникальным"
      end
    end
  
    def destroy
        @discipline.materials.destroy_all
        @discipline.destroy
        redirect_to disciplines_path, notice: 'Дисциплина успешно удалена!'
    end

    def detach_material
      @discipline = Discipline.find(params[:id])
      @material = @discipline.materials.find(params[:material_id])
      @discipline.materials.destroy(@material)
    
      respond_to do |format|
        format.js
      end
    end
    private

      def set_discipline
        @discipline = Discipline.find(params[:id])
      end
    
      def discipline_params
        params.require(:discipline).permit(:name, :description, material_ids: [])
      end
  end

app/controllers/moderator/disciplines_controller.rb
class Moderator::DisciplinesController < ModeratorController
    before_action :check_access_to_discipline, only: [:show, :edit, :update, :destroy]
    respond_to :js, only: [:create]

    def index
      if current_user.has_role?('admin')
        @disciplines = Discipline.page(params[:page]).per(5)
      else
        @disciplines = Discipline.joins(role_users: :role)
                                  .where(role_users: { user_id: current_user.id, roles: { name: 'moderator' } })
                                  .page(params[:page]).per(5)
      end
    end

    def show
      @materials = @discipline.materials
    end

    def new
        @discipline = Discipline.new
        # По-хорошему нужно для добавления сразу дисциплин
        # @material = Material.new
    end

    def create
      @discipline = Discipline.new(discipline_params)
      if @discipline.save
        moderator = current_user.get_role_user('moderator')
        if !moderator.nil?
          @discipline.role_users << moderator
        end
        redirect_to moderator_disciplines_path, notice: 'Дисциплина успешно создана!'
      else
        # Не используется, но мб есть смысл здесь сразу делать запрос, а не в бд
        # @available_materials = Material.all
        redirect_to request.referer, alert: "Имя должно быть уникальным"
      end
    end
    
    def update_order
      Rails.logger.info params[:ordered_ids].inspect
      params[:ordered_ids].each_with_index do |id, index|
        Material.find(id).update(order: index)
      end
      # Ответ сервера (например, статус 200 OK)
    end
  

    def edit
      @discipline = Discipline.find(params[:id])
      @materials = @discipline.materials
    end

    def update
      if @discipline.update(discipline_params)
        redirect_to moderator_discipline_path(@discipline), notice: 'Дисциплина успешно обновлена!'
      else
        @available_materials = Material.all
        redirect_to request.referer, alert: "Имя должно быть уникальным"
      end
    end

    def destroy
      @discipline.materials.destroy_all
      @discipline.destroy
      redirect_to moderator_disciplines_path, notice: 'Дисциплина успешно удалена!'
    end

    def detach_material
      @discipline = Discipline.find(params[:id])
      @material = @discipline.materials.find(params[:material_id])
      @discipline.materials.destroy(@material)
    
      respond_to do |format|
        format.js
      end
    end


    private

      def check_access_to_discipline
        @discipline = Discipline.find(params[:id])
        redirect_to root_path, alert: 'Доступ запрещен' unless @discipline.role_users.exists?(user_id: current_user.id, role_id: Role.find_by(name: 'moderator')&.id) || @is_admin
      end
    
      def discipline_params
        params.require(:discipline).permit(:name, :description, material_ids: [])
      end
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
    def get_role_user_by_role(role)
        RoleUser.joins(:role).find_by(users: { id: current_user.id }, roles: { name: role })
    end
end

app/helpers/moderator/disciplines_helper.rb
module Moderator::DisciplinesHelper
end

app/views/disciplines/edit.html.erb
<h1>Редактировать дисциплину</h1>

<%= form_with(model: @discipline, local: true) do |form| %>
<div>
    <%= form.label :name, 'Название дисциплины' %>
    <%= form.text_field :name %>
</div>
<h3>Список материалов:</h3>
<%= render partial: 'materials/materials_list', locals: { materials: @discipline.materials, discipline: @discipline } %>
<div>
    <%= form.submit 'Сохранить' %>
</div>
<% end %>

<div id="addMaterialModal" style="display: none;">
<%= render partial: 'materials/new_modal', locals: { discipline: @discipline } %>
</div>

<!-- Add the JavaScript to handle the modal -->
<script>
document.addEventListener('DOMContentLoaded', function() {
    $(document).ready(function() {
        $('#addMaterialLink').on('click', function() {
          $('#addMaterialModal').css('display', 'block');
        });
    });

// Handle material deletion
$(document).on('click', '.delete-material-link', function(event) {
  event.preventDefault();
  var materialId = $(this).data('material-id');
  deleteMaterial(materialId);
});

$(document).on('click', '.delete-material-link', function (event) {
    event.preventDefault();
    var materialId = $(this).data('material-id');
    deleteMaterial(materialId);
  });

  function deleteMaterial(materialId) {
    // Get CSRF token
    var csrfToken = $('meta[name="csrf-token"]').attr('content');

    // Perform asynchronous request to delete material
    $.ajax({
      url: `/disciplines/<%= @discipline.id %>/detach_material/${materialId}`,
      type: 'DELETE',
      dataType: 'json',
      headers: {
        'Content-Type': 'application/json',
        'X-CSRF-Token': csrfToken
      },
      success: function () {
        console.log('Материал успешно удален');
        // Reload the page after successful deletion
        location.reload();
      },
      error: function () {
        console.error('Ошибка при удалении материала');
      }
    });
  }
});
</script>

app/views/disciplines/index.html.erb
<div class="my-3 p-3 bg-body rounded shadow-sm">
  <div class="d-flex flex-wrap align-items-center pb-2 border-bottom">
    <h3 class=" pb-2 mb-0 col-12 col-lg-auto me-lg-auto">Дисциплины</h3>
    <div class="text-end">
      <%= button_to '+ Создать', new_discipline_path, :method => :get, type: "button", class: "btn btn-outline-secondary" %>
    </div>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Название</th>
        <th scope="col">Материалы</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
    <% @disciplines.each do |discipline| %>
        <tr>
          <td><%= label_tag "#{discipline.name}" %></td>
          <td><%= label_tag "#{discipline.materials.length}" %></td>
          <td>
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
              <%= link_to 'Подробнее', discipline, class: "btn btn-outline-secondary btn-sm" %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/disciplines/new.html.erb
<div class="my-3 p-3 bg-body rounded shadow-sm">
  <div class="d-flex flex-wrap align-items-center pb-2 border-bottom">
    <h3 class=" pb-2 mb-0 col-12 col-lg-auto me-lg-auto">Создание дисциплины</h3>
    <div class="text-end">
      <%= button_to 'Отмена', disciplines_path, :method => :get, type: "button", class: "btn btn-outline-secondary" %>
    </div>
  </div>

  <%= form_with(model: @discipline, local: true) do |f| %>
    <div class="form-floating">
      <%= f.text_field :name, class: "form-control", id: "floatingInput", placeholder: ""  %>
      <%= f.label "Название", for: "floatingInput", class: "form-label" %>
    </div>

    <div class="form-floating">
      <%= f.text_field :description, class: "form-control", id: "floatingInput", placeholder: ""  %>
      <%= f.label "Описание", for: "floatingInput", class: "form-label" %>
    </div>
    
    <%= f.submit 'Создать', class: "btn btn-primary w-100 py-2" %>
  <% end %>
</div>

app/views/disciplines/show.html.erb
<div class="my-3 p-3 bg-body rounded shadow-sm">
  <div class="d-flex flex-wrap align-items-center pb-2">
    <h3 class=" pb-2 mb-0 col-12 col-lg-auto me-lg-auto"><%= @discipline.name %></h3>
  </div>
  <div class="lead my-2 pb-2 border-bottom">Описание: <%= @discipline.description %></div>
  <%= render partial: 'materials/materials_list', locals: { materials: @discipline.materials, discipline: @discipline } %>
</div>