config/routes.rb
Rails.application.routes.draw do
  # get 'static_pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_for :users, controllers: { registrations: 'users/registrations'}

  resources :disciplines do
    resources :materials, only: [:new, :create, :index, :show] do
      member do
        patch 'update_access', to: 'materials#update_access', as: :update_access
      end
    end  
    member do
      delete 'detach_material/:material_id', to: 'disciplines#detach_material', as: :detach_material
    end
  end
  resources :schedules do
    get 'load_disciplines', on: :collection
    get 'carousel', on: :member
  end
  resources :users, only: [:edit, :update, :show]
  get 'search_users', to: 'users#search_users'
  get 'search_users_list', to: 'users#search_users_list'
  
  resources :groups
  resources :courses do
    member do
      get 'teachers' => 'courses#edit_teachers'
      patch 'teachers' => 'courses#update_teachers'
      get 'students' => 'courses#edit_students'
      patch 'students' => 'courses#update_students'
    end
  end

  namespace :moderator do
    resources :courses do
      member do
        get 'teachers' => 'courses#edit_teachers'
        patch 'teachers' => 'courses#update_teachers'
        get 'students' => 'courses#edit_students'
        patch 'students' => 'courses#update_students'
        get 'disciplines' => 'courses#edit_disciplines'
        patch 'disciplines' => 'courses#update_disciplines'
      end
    end
    resources :disciplines do
      resources :materials, only: [:new, :create, :show, :index] do
        member do
          patch 'update_access', to: 'materials#update_access', as: :update_access
        end
      end  
      member do
        delete 'detach_material/:material_id', to: 'disciplines#detach_material', as: :detach_material
        post 'update_order', to: 'disciplines#update_order', as: :update_order
      end
    end
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update] do
      # member do
      #   patch 'toggle_block' => 'users#toggle_block'
      # end
    end
    root "users#index"
    resources :roles
    resources :groups do
      # member do
      #   get 'search_users' => 'groups#search_users'
      #   
      # end
    end
  end

  resources :chats
  resources :messages, only: [:create]

  root "static_pages#home"
end

app/models/group.rb
class Group < ApplicationRecord
    has_and_belongs_to_many :users
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < AdminController
    def index
        @groups = Group.page(params[:page]).per(5)
    end

    def show
        @group = Group.find_by!(id: params[:id])
        @users_in_group = @group.users.page(params[:page]).per(5)
    end

    def new
        @group = Group.new
        @users = User.all
    end

    def create
        @group = Group.new(group_params)
        Group.transaction do
            if @group.save
              @group.user_ids = params[:user_ids].reject(&:blank?) if params[:user_ids].present?
              redirect_to admin_group_path(@group), notice: 'Группа успешно создана.'
            else
              render :new, status: :unprocessable_entity
            end
        end
    rescue ActiveRecord::RecordInvalid
        render :new, status: :unprocessable_entity
    end

    def edit
        @group = Group.find(params[:id])
        @users = User.all
    end


    # TODO: Переделать обновление списка пользователей в группе (сделать как при создании)
    def update
        @group = Group.find(params[:id])
        Group.transaction do
            if @group.update(group_params)
              @group.user_ids = Array.wrap(params[:group][:user_ids])
              redirect_to admin_group_path(@group), notice: 'Группа успешно обновлена.'
            else
              render 'edit', status: :unprocessable_entity
            end
        end
    rescue ActiveRecord::RecordInvalid
      render 'edit', status: :unprocessable_entity
    end

    def destroy
        @group = Group.find(params[:id])
        @group.destroy
        redirect_to admin_groups_path, notice: "Группа была удалена"
    end

    private
        def group_params
            params.require(:group).permit(:name, :description, :user_ids)
        end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    def index
        @groups = Group.all
    end

    def show
        @group = Group.find(params[:id])
        @users_in_group = @group.users
    end

    def new
        @group = Group.new
        @users = User.all
    end

    def create
        @group = Group.new(group_params) 
        if @group.save
            if params[:group][:user_ids].present?
                # @users_to_add = User.where(id: params[:group][:user_ids])
                # @group.users << @users_to_add if @users_to_add.present?
                @group.user_ids = params[:group][:user_ids]
            end
            redirect_to @group
        else
            render 'new'
        end
    end

    def edit
        @group = Group.find(params[:id])
        @users = User.all
    end

    def update
        @group = Group.find(params[:id])
        if @group.update(group_params)
            @group.user_ids = params[:group][:user_ids]
            flash[:notice] = "Группа обновлена"
            redirect_to @group
        else
            render 'edit'
        end
    end

    def destroy
        flash[:notice] = "Группа была удалена"
        @group = Group.find(params[:id])
        @group.destroy
        redirect_to groups_path
    end

    # def update_users
    #     @group = Group.find(params[:id])
    
    #     # Обновляем список принадлежащих группе пользователей
    #     @group.user_ids = params[:group][:user_ids]

    #     flash[:notice] = "Группа успешно обновлена"
    #     # Перенаправляем пользователя после сохранения изменений
    #     redirect_to @group
    # end

    # def add_user
    #     # debugger
    #     @group = Group.find(params[:id])
    #     @user = User.find(params[:user][:id])
    #     @group.users << @user
    
        
    #     redirect_to group_path(@group)
    # end

    # def add_users
    #     @group = Group.find(params[:id])
    #     @userss = User.where.not(id: @group.user_ids)

    #     # debugger
    
    #     if params[:group][:user_ids].present?
    #       @users_to_add = User.where(id: params[:group][:user_ids])
    #       @group.users << @users_to_add if @users_to_add.present?
    #     end
    
    #     redirect_to group_path(@group)
    # end

    # def del_user
    #     @group = Group.find(params[:id])
    #     @user = User.find()
    # end

    private

        def group_params
            params.require(:group).permit(:name, :description, :user_ids)
        end
    # debugger
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
  <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
    <p class="h1 mb-3 fw-bold">Рeдактирование</p>
  </ul>

  <div class="text-end">
    <%= button_to 'Отмена', group_path, :method => :get, type: "button", class: "btn btn-outline-secondary" %>
  </div>
</div>

<%= form_for @group do |f| %>
  <div class="form-floating">
    <%= f.text_field :name, class: "form-control", id: "floatingInput", placeholder: "name@example.com"  %>
    <%= f.label "Название", for: "floatingInput", class: "form-label" %>
  </div>

  <div class="form-floating">
    <%= f.text_area :description, class: "form-control", id: "floatingInput", placeholder: "name@example.com"  %>
    <%= f.label "Описание", for: "floatingInput", class: "form-label" %>
  </div>

  <%# <%= f.label :description, for: "formControlInput", class: "form-label" %>
  <%# <%= f.text_area :description, class: "form-control", id: "formControlInput", placeholder: "Описание" %>
  
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">Фамилия</th>
        <th scope="col">Имя</th>
        <th scope="col">Отчество</th>
      </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
        <tr>
          <th scope="row">
            <%= check_box_tag 'group[user_ids][]', user.id, @group.users.include?(user) %>
          </th>
          <td><%= label_tag "#{user.user_profile.last_name}" %></td>
          <td><%= label_tag "#{user.user_profile.first_name}" %></td>
          <td><%= label_tag "#{user.user_profile.second_name}" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>           

  <%= f.submit 'Сохранить', class: "btn btn-primary w-100 py-2" %>
<% end %>

app/views/groups/index.html.erb
<div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
  <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
    <p class="h1 mb-3 fw-bold">Группы</p>
  </ul>

  <div class="text-end">
    <%= button_to '+ Создать', new_group_path, :method => :get, type: "button", class: "btn btn-outline-secondary" %>
  </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Название</th>
      <th scope="col">Пользователи</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  <% @groups.each do |group| %>
      <tr>
        <td><%= label_tag "#{group.name}" %></td>
        <td><%= label_tag "#{group.users.length}" %></td>
        <td>
          <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <%= link_to 'Edit', edit_group_path(group), class: "btn btn-outline-secondary btn-sm" %>
            <%= button_to 'Delete', group, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-outline-secondary btn-sm" %>
            <%= link_to 'Show', group, class: "btn btn-outline-secondary btn-sm" %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>                     

app/views/groups/new.html.erb
<p class="h1 mb-3 fw-bold">Создание группы</p>
<%= form_for @group do |f| %>
  <div class="form-floating">
    <%= f.text_field :name, class: "form-control", id: "floatingInput", placeholder: ""  %>
    <%= f.label "Название", for: "floatingInput", class: "form-label" %>
  </div>

  <div class="form-floating">
    <%= f.text_area :description, class: "form-control", id: "floatingInput", placeholder: ""  %>
    <%= f.label "Описание", for: "floatingInput", class: "form-label" %>
  </div>

  <%# <%= f.label :description, for: "formControlInput", class: "form-label" %>
  <%# <%= f.text_area :description, class: "form-control", id: "formControlInput", placeholder: "Описание" %>
  
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">Фамилия</th>
        <th scope="col">Имя</th>
        <th scope="col">Отчество</th>
      </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
        <tr>
          <th scope="row">
            <%= check_box_tag 'group[user_ids][]', user.id, @group.users.include?(user) %>
          </th>
          <td><%= label_tag "#{user.user_profile.last_name}" %></td>
          <td><%= label_tag "#{user.user_profile.first_name}" %></td>
          <td><%= label_tag "#{user.user_profile.second_name}" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>           

  <%= f.submit 'Создать', class: "btn btn-primary w-100 py-2" %>
<% end %>