config/routes.rb
Rails.application.routes.draw do
  # get 'static_pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_for :users, controllers: { registrations: 'users/registrations'}

  resources :disciplines do
    resources :materials, only: [:new, :create, :index, :show] do
      member do
        patch 'update_access', to: 'materials#update_access', as: :update_access
      end
    end  
    member do
      delete 'detach_material/:material_id', to: 'disciplines#detach_material', as: :detach_material
    end
  end
  resources :schedules do
    get 'load_disciplines', on: :collection
    get 'carousel', on: :member
  end
  resources :users, only: [:edit, :update, :show]
  get 'search_users', to: 'users#search_users'
  get 'search_users_list', to: 'users#search_users_list'
  
  resources :groups
  resources :courses do
    member do
      get 'teachers' => 'courses#edit_teachers'
      patch 'teachers' => 'courses#update_teachers'
      get 'students' => 'courses#edit_students'
      patch 'students' => 'courses#update_students'
    end
  end

  namespace :moderator do
    resources :courses do
      member do
        get 'teachers' => 'courses#edit_teachers'
        patch 'teachers' => 'courses#update_teachers'
        get 'students' => 'courses#edit_students'
        patch 'students' => 'courses#update_students'
        get 'disciplines' => 'courses#edit_disciplines'
        patch 'disciplines' => 'courses#update_disciplines'
      end
    end
    resources :disciplines do
      resources :materials, only: [:new, :create, :show, :index] do
        member do
          patch 'update_access', to: 'materials#update_access', as: :update_access
        end
      end  
      member do
        delete 'detach_material/:material_id', to: 'disciplines#detach_material', as: :detach_material
        post 'update_order', to: 'disciplines#update_order', as: :update_order
      end
    end
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update] do
      # member do
      #   patch 'toggle_block' => 'users#toggle_block'
      # end
    end
    root "users#index"
    resources :roles
    resources :groups do
      # member do
      #   get 'search_users' => 'groups#search_users'
      #   
      # end
    end
  end

  resources :chats
  resources :messages, only: [:create]

  root "static_pages#home"
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    has_many :course_disciplines
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
 def new
   @schedule = Schedule.new
   @courses = Course.all
 end
 def create
  start_times_hash = params[:schedule][:start_times]
  start_times = start_times_hash.values
  end_times_hash = params[:schedule][:end_times]
  end_times = end_times_hash.values
  course_discipline = CourseDiscipline.find_by(course_id: params[:schedule][:course_id], discipline_id: params[:schedule][:discipline_id])
  course_discipline_id = course_discipline&.id
  params[:schedule] = params[:schedule].merge(course_discipline_id: course_discipline_id)
  start_times.each_with_index do |start_time, index|
    @schedule = Schedule.new(
      course_discipline_id: params[:schedule][:course_discipline_id],
      start_time: start_time,
      end_time: end_times[index]
    )
    unless unique_schedule?
      redirect_to request.referer, alert: "Запись об этом занятии уже создана" and return
    end
    @schedule.save
  end
  redirect_to request.referer, notice: 'Новые записи в расписании созданы'
end

def carousel
  @course = Course.find(params[:id])
  selected_date = "#{params[:selected_date]}-01"&.to_date || Date.current
  @schedules_by_day = generate_schedules_by_day(selected_date)
  respond_to do |format|
    format.html { render partial: 'carousel' }
  end
end

 def load_disciplines
   course_id = params[:course_id]
   if course_id
     course = Course.find(course_id)
     @disciplines = course.disciplines
   else
     @disciplines = []
   end
   respond_to do |format|
     format.json { render json: @disciplines }
   end
 end
#не используется
 def show
  @course = Course.find(params[:id])
  @schedules = Schedule.joins(course_disciplines: :discipline).where(course_disciplines: { course_id: @course.id })
  selected_date = params[:selected_date]&.to_date || Date.current
  @schedules_by_day = generate_schedules_by_day(selected_date)
 end
#пока не используется
 def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    redirect_to request.referer, notice: "Запись удалена"
 end


 private
#пока не используется
 def schedule_params
  course_discipline = CourseDiscipline.find_by(course_id: params[:schedule][:course_id], discipline_id: params[:schedule][:discipline_id])
  course_discipline_id = course_discipline&.id
  params.require(:schedule).permit(start_times: [], end_times: []).merge(course_discipline_id: course_discipline_id)
 end

 def unique_schedule?
  Schedule.where(
    course_discipline_id: @schedule.course_discipline_id,
    start_time: @schedule.start_time,
    end_time: @schedule.end_time
  ).none?
  end

  def generate_schedules_by_day(selected_date)
    start_date = selected_date.beginning_of_month
    end_date = selected_date.end_of_month
    (start_date..end_date).map do |date|
      schedules = Schedule.joins("INNER JOIN course_disciplines ON course_disciplines.id=schedules.course_discipline_id
      INNER JOIN disciplines ON disciplines.id=course_disciplines.discipline_id")
        .where(course_disciplines: { course_id: @course.id })
        .where('DATE(schedules.start_time) = ?', date)
      puts schedules.inspect
    { date: date, schedules: schedules }
    end
  end

#пока не используется
  def overlapping_time?(schedule1, schedule2)
    schedule1_start_time = schedule1.start_time
    schedule1_end_time = schedule1.end_time
    schedule2_start_time = schedule2.start_time
    schedule2_end_time = schedule2.end_time
  
    (schedule1_start_time..schedule1_end_time).overlaps?(schedule2_start_time..schedule2_end_time)
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_carousel.html.erb
<div id="scheduleCarousel" class="carousel slide" data-bs-ride="carousel" data-bs-interval="86400000">
  <div class="carousel-inner">
    <% @schedules_by_day.each_with_index do |day, index| %>
      <div class="carousel-item <%= 'active' if index == 0 %>">
      <div class="carousel-arrow">
        <a class="carousel-control-prev" href="#scheduleCarousel" role="button" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </a>
        <% months_in_russian = ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'] %>
        <% days_of_week_in_russian = ['Воскресенье', 'Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота'] %>
        <h3 style="text-align: center;">
          <%= "#{days_of_week_in_russian[day[:date].wday]}, #{day[:date].strftime('%d')} #{months_in_russian[day[:date].month - 1]} #{day[:date].strftime('%Y')}" %>
        </h3>
        <a class="carousel-control-next" href="#scheduleCarousel" role="button" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </a>
      </div>
        <table class="table">
          <thead>
            <tr>
              <th>Время</th>
              <th>Дисциплины</th>
            </tr>
          </thead>
          <tbody>
          <% day[:schedules].each do |schedule| %>
            <tr>
              <td><%= schedule.start_time.strftime('%H:%M') %> - <%= schedule.end_time.strftime('%H:%M') %></td>
              <td>
                <% course_discipline = CourseDiscipline.find(schedule.course_discipline_id) %>
                <% discipline_name = Discipline.find(course_discipline.discipline_id).name %>
                <%= discipline_name %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
</div>

app/views/schedules/_show.html.erb
<div class="input-group mb-3">
  <span class="input-group-text">Выберите месяц:</span>
  <input type="month" class="form-control" id="monthPicker" value="<%= Time.now.strftime('%Y-%m') %>">
</div>
<div id="scheduleCarousel" class="carousel slide" data-bs-ride="carousel" data-bs-interval="86400000">
  <div class="carousel-inner">
  <% current_date = Date.current %>
    <% schedules_by_day.each_with_index do |day, index| %>
      <div class="carousel-item <%= 'active' if day[:date] == current_date %>">
      <div class="carousel-arrow">
        <a class="carousel-control-prev" href="#scheduleCarousel" role="button" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </a>
        <% months_in_russian = ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'] %>
        <% days_of_week_in_russian = ['Воскресенье', 'Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота'] %>
        <h3 style="text-align: center;">
          <%= "#{days_of_week_in_russian[day[:date].wday]}, #{day[:date].strftime('%d')} #{months_in_russian[day[:date].month - 1]} #{day[:date].strftime('%Y')}" %>
        </h3>
        <a class="carousel-control-next" href="#scheduleCarousel" role="button" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </a>
      </div>
        <table class="table">
          <thead>
            <tr>
              <th>Время</th>
              <th>Дисциплины</th>
            </tr>
          </thead>
          <tbody>
          <% day[:schedules].each do |schedule| %>
            <tr>
              <td><%= schedule.start_time.strftime('%H:%M') %> - <%= schedule.end_time.strftime('%H:%M') %></td>
              <td>
                <% course_discipline = CourseDiscipline.find(schedule.course_discipline_id) %>
                <% discipline_name = Discipline.find(course_discipline.discipline_id).name %>
                <%= discipline_name %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
</div>
<script>
  document.addEventListener('turbo:load', function() {
    var current_date = new Date().toISOString().split('T')[0]; // Получаем сегодняшнюю дату в формате YYYY-MM-DD
    var monthPicker = document.getElementById('monthPicker');
    monthPicker.value = current_date.substring(0, 7); // Устанавливаем сегодняшний месяц и год в качестве значения monthPicker

    monthPicker.addEventListener('change', function() {
      var selectedDate = monthPicker.value;
      loadCarousel(selectedDate);
    });

    function loadCarousel(selectedDate) {
      var url = '<%= carousel_schedule_path(@course) %>';
      var params = { selected_date: selectedDate };
      console.log(url + '?' + new URLSearchParams(params));

      fetch(url + '?' + new URLSearchParams(params))
        .then(response => response.text())
        .then(data => {
          console.log(data);
          document.getElementById('scheduleCarousel').outerHTML = data;})
        .catch(error => console.error('Error:', error));
    }
  });
</script>

app/views/schedules/new.html.erb
<h1>Новое расписание</h1>
<div class="row">
  <div class="col-md-8">
    <%= form_with(model: @schedule, local: true, class: 'needs-validation', novalidate: true) do |form| %>

      <div class="mb-3">
        <%= form.label :course_id, 'Выберите курс', class: 'form-label' %>
        <%= form.collection_select :course_id, @courses, :id, :name, { prompt: 'Выберите курс' }, { class: 'form-select', required: true } %>
      </div>

      <div id="disciplines" class="mb-3" style="display: none;">
        <%= form.label :discipline_id, 'Выберите дисциплину', class: 'form-label' %>
        <%= form.collection_select :discipline_id, [], :id, :name, { prompt: 'Выберите дисциплину' }, { class: 'form-select', required: true } %>
      </div>

      <div id="schedule-fields" class="mb-3" style="display: none;">
        <div class="row g-3 time-fields">
          <div class="col-md-6">
            <label>Время начала</label>
            <input type="datetime-local" name="schedule[start_times][0]" value="" id="schedule_start_time">
          </div>
          <div class="col-md-6">
            <label>Время окончания</label>
            <input type="datetime-local" name="schedule[end_times][0]" value="" id="schedule_end_time">
          </div>
        </div>
      </div>

      <div id="add-time-link" class="mb-3" style="display: none;">
        <%= link_to 'Добавить еще время', 'javascript:void(0);', class: 'btn btn-outline-secondary', id: 'add-time' %>
      </div>

      <div>
        <%= form.submit 'Создать расписание', class: 'btn btn-primary' %>
      </div>

    <% end %>
  </div>
</div>
<script>
  document.addEventListener('turbo:load', function() {
    var courseSelect = document.querySelector('#schedule_course_id');
    var disciplinesDiv = document.getElementById('disciplines');
    var addTimeLink = document.getElementById('add-time');
    var scheduleFieldsDiv = document.getElementById('schedule-fields');
    var addTimeButton = document.getElementById('add-time-link')
    var startTimeInput = document.querySelector('#schedule_start_time');
    var endTimeInput = document.querySelector('#schedule_end_time');

    courseSelect.addEventListener('change', function() {
      var courseId = courseSelect.value;
      if (courseId) {
        // Загрузить дисциплины для выбранного курса
        fetch(`/schedules/load_disciplines?course_id=${courseId}`)
          .then(response => response.json())
          .then(data => {
            var disciplineSelect = document.querySelector('#schedule_discipline_id');
            disciplineSelect.innerHTML = '<option value="">Выберите дисциплину</option>';
            data.forEach(discipline => {
              var option = document.createElement('option');
              option.value = discipline.id;
              option.text = discipline.name;
              disciplineSelect.add(option);
            });
          });

        // Показать блок с дисциплинами
        disciplinesDiv.style.display = 'block';
      } else {
        // Скрыть блок с дисциплинами
        disciplinesDiv.style.display = 'none';
      }
    });
    startTimeInput.addEventListener('change', function() {
        var startTime = new Date(startTimeInput.value);
        var endTime = new Date(startTime.getTime() + 5400000);
        var timezoneOffset = startTime.getTimezoneOffset() * 60000; // получаем разницу в минутах и переводим в миллисекунды
        endTimeInput.value = new Date(endTime - timezoneOffset).toISOString().slice(0, -5);
    });  

    var disciplineSelect = document.querySelector('#schedule_discipline_id');
    disciplineSelect.addEventListener('change', function() {
      var disciplineId = disciplineSelect.value;
      if (disciplineId) {
        // Показать блок с полями расписания
        addTimeButton.style.display = 'block';
        scheduleFieldsDiv.style.display = 'block';
      } else {
        // Скрыть блок с полями расписания
        addTimeButton.style.display = 'none';
        scheduleFieldsDiv.style.display = 'none';
      }
    });
    var timeFieldsCounter = 1;

  addTimeLink.addEventListener('click', function() {

  // Create a new div for time fields
  var timeFieldsDiv = document.createElement('div');
  timeFieldsDiv.className = 'time-fields';

  // Create labels and input fields for start_time
  var startTimeLabel = document.createElement('label');
  startTimeLabel.textContent = 'Время начала';

  var startTimeInput = document.createElement('input');
  startTimeInput.type = 'datetime-local';
  startTimeInput.name = `schedule[start_times][${timeFieldsCounter}]`;
  startTimeInput.value = startTimeInput.value || ''; // Set initial value

  // Create labels and input fields for end_time
  var endTimeLabel = document.createElement('label');
  endTimeLabel.textContent = 'Время окончания';

  var endTimeInput = document.createElement('input');
  endTimeInput.type = 'datetime-local';
  endTimeInput.name = `schedule[end_times][${timeFieldsCounter}]`;
  endTimeInput.value = endTimeInput.value || ''; // Set initial value

  // Append labels and input fields to the timeFieldsDiv
  timeFieldsDiv.appendChild(startTimeLabel);
  timeFieldsDiv.appendChild(startTimeInput);
  timeFieldsDiv.appendChild(endTimeLabel);
  timeFieldsDiv.appendChild(endTimeInput);

  // Append the timeFieldsDiv to the scheduleFieldsDiv
  scheduleFieldsDiv.appendChild(timeFieldsDiv);
  var startTimeInput = document.querySelector(`input[name="schedule[start_times][${timeFieldsCounter}]"]`);
  var endTimeInput = document.querySelector(`input[name="schedule[end_times][${timeFieldsCounter}]"]`);

  startTimeInput.addEventListener('change', function() {
    var startTime = new Date(startTimeInput.value);
    var endTime = new Date(startTime.getTime() + 5400000);
    var timezoneOffset = startTime.getTimezoneOffset() * 60000;
    endTimeInput.value = new Date(endTime - timezoneOffset).toISOString().slice(0, -5);
  });

  // Update the counter for unique field names
  timeFieldsCounter++;
});
  
});
</script>

app/views/schedules/show.html.erb
<h1><%= @course.name %> - Расписание</h1>

<div class="input-group mb-3">
  <span class="input-group-text">Выберите месяц:</span>
  <input type="month" class="form-control" id="monthPicker" value="<%= Time.now.strftime('%Y-%m') %>">
</div>
<div class="carousel-container">
<a class="carousel-control-prev" href="#scheduleCarousel" role="button" data-bs-slide="prev">
  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
  <span class="visually-hidden">Previous</span>
</a>

  <a class="carousel-control-next" href="#scheduleCarousel" role="button" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </a>
</div>
<div id="scheduleCarousel" class="carousel slide" data-bs-ride="carousel" data-bs-interval="86400000">
  <div class="carousel-inner">
    <% @schedules_by_day.each_with_index do |day, index| %>
      <div class="carousel-item <%= 'active' if index == 0 %>">
      <% months_in_russian = ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'] %>
      <h3 style="text-align: center;"><%= "#{months_in_russian[day[:date].month - 1]} #{day[:date].strftime('%d, %Y')}" %></h3>
        <table class="table">
          <thead>
            <tr>
              <th>Время</th>
              <th>Дисциплины</th>
            </tr>
          </thead>
          <tbody>
          <% day[:schedules].each do |schedule| %>
            <tr>
              <td><%= schedule.start_time.strftime('%H:%M') %> - <%= schedule.end_time.strftime('%H:%M') %></td>
              <td>
                <% course_discipline = CourseDiscipline.find(schedule.course_discipline_id) %>
                <% discipline_name = Discipline.find(course_discipline.discipline_id).name %>
                <%= discipline_name %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
</div>
<script>
  document.addEventListener('DOMContentLoaded', function() {
    var monthPicker = document.getElementById('monthPicker');
    monthPicker.addEventListener('change', function() {
      var selectedDate = monthPicker.value;
      loadCarousel(selectedDate);
    });
    function loadCarousel(selectedDate) {
      var url = '<%= carousel_schedule_path(@course) %>';
      var params = { selected_date: selectedDate };
      console.log(url + '?' + new URLSearchParams(params));

      fetch(url + '?' + new URLSearchParams(params))
        .then(response => response.text())
        .then(data => {
          console.log(data);
          document.getElementById('scheduleCarousel').outerHTML = data;})
        .catch(error => console.error('Error:', error));
    }
  });
</script>