config/routes.rb
Rails.application.routes.draw do
  # get 'static_pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_for :users, controllers: { registrations: 'users/registrations'}

  resources :disciplines do
    resources :materials, only: [:new, :create, :index, :show] do
      member do
        patch 'update_access', to: 'materials#update_access', as: :update_access
      end
    end  
    member do
      delete 'detach_material/:material_id', to: 'disciplines#detach_material', as: :detach_material
    end
  end
  resources :schedules do
    get 'load_disciplines', on: :collection
    get 'carousel', on: :member
  end
  resources :users, only: [:edit, :update, :show]
  get 'search_users', to: 'users#search_users'
  get 'search_users_list', to: 'users#search_users_list'
  
  resources :groups
  resources :courses do
    member do
      get 'teachers' => 'courses#edit_teachers'
      patch 'teachers' => 'courses#update_teachers'
      get 'students' => 'courses#edit_students'
      patch 'students' => 'courses#update_students'
    end
  end

  namespace :moderator do
    resources :courses do
      member do
        get 'teachers' => 'courses#edit_teachers'
        patch 'teachers' => 'courses#update_teachers'
        get 'students' => 'courses#edit_students'
        patch 'students' => 'courses#update_students'
        get 'disciplines' => 'courses#edit_disciplines'
        patch 'disciplines' => 'courses#update_disciplines'
      end
    end
    resources :disciplines do
      resources :materials, only: [:new, :create, :show, :index] do
        member do
          patch 'update_access', to: 'materials#update_access', as: :update_access
        end
      end  
      member do
        delete 'detach_material/:material_id', to: 'disciplines#detach_material', as: :detach_material
        post 'update_order', to: 'disciplines#update_order', as: :update_order
      end
    end
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update] do
      # member do
      #   patch 'toggle_block' => 'users#toggle_block'
      # end
    end
    root "users#index"
    resources :roles
    resources :groups do
      # member do
      #   get 'search_users' => 'groups#search_users'
      #   
      # end
    end
  end

  resources :chats
  resources :messages, only: [:create]

  root "static_pages#home"
end

app/models/discipline.rb
class Discipline < ApplicationRecord
    has_and_belongs_to_many :role_users
    has_many :materials
    has_many :course_disciplines
    has_many :courses, through: :course_disciplines
    
    validates :name, presence: true, uniqueness: true
end

app/controllers/disciplines_controller.rb
# controllers/disciplines_controller.rb
class DisciplinesController < ApplicationController
    before_action :set_discipline, only: [:show, :edit, :update, :destroy]
    respond_to :js, only: [:create]
  
    def index
      @disciplines = Discipline.all
    end
  
    def new
      @discipline = Discipline.new
      @material = Material.new
    end
  
    def create
      @discipline = Discipline.new(discipline_params)
      if @discipline.save
        moderator = current_user.get_role_user('moderator')
        if !moderator.nil?
          @discipline.role_users << moderator
        end
        redirect_to disciplines_path, notice: 'Дисциплина успешно создана!'
      else
        @available_materials = Material.all
        redirect_to request.referer, alert: "Имя должно быть уникальным"
      end
    end
  
    def show
      @materials = @discipline.materials
    end
  
    def edit
      @discipline = Discipline.find(params[:id])
      @materials = @discipline.materials
    end
  
    def update
      if @discipline.update(discipline_params)
        redirect_to @discipline, notice: 'Дисциплина успешно обновлена!'
      else
        @available_materials = Material.all
        redirect_to request.referer, alert: "Имя должно быть уникальным"
      end
    end
  
    def destroy
        @discipline.materials.destroy_all
        @discipline.destroy
        redirect_to disciplines_path, notice: 'Дисциплина успешно удалена!'
    end

    def detach_material
      @discipline = Discipline.find(params[:id])
      @material = @discipline.materials.find(params[:material_id])
      @discipline.materials.destroy(@material)
    
      respond_to do |format|
        format.js
      end
    end
    private

      def set_discipline
        @discipline = Discipline.find(params[:id])
      end
    
      def discipline_params
        params.require(:discipline).permit(:name, :description, material_ids: [])
      end
  end

app/controllers/moderator/courses_controller.rb
class Moderator::CoursesController < ModeratorController
    # Проверка на то, что пользователь либо админ, либо модератор этого курса
    before_action :check_access_to_discipline, 
            only: [:show, :edit, :update, :destroy, :edit_teachers, :update_teachers, :edit_students, :update_students, :edit_disciplines, :update_disciplines]

    def index
        # Если админ, то получаем все курсы 
        if current_user.has_role?('admin')
            @courses = Course.page(params[:page]).per(5)
        # Иначе получаем только те, на которых являемся модератором
        else
            @courses = Course.joins(role_users: :role)
                                .where(role_users: { user_id: current_user.id, roles: { name: 'moderator' } })
                                .page(params[:page]).per(5)
        end
    end

    # На странице курсы выводим преподавателей, дисциплины, студентов
    # TODO: переделать поиск преподавателей, так как они добавляются не на сам курс, а на дисциплину_на_курсе
    #       к самому курсу привязаны только студенты и модераторы 
    def show
        @disciplines = @course.disciplines
        @teachers = RoleUser.joins(:role, :courses).where(roles: { name: 'teacher'}, courses: { id: params[:id] })
        @students = RoleUser.joins(:role, :courses).where(roles: { name: 'student'}, courses: { id: params[:id] })
        @course = Course.find(params[:id])
        @schedules = Schedule.joins(course_disciplines: :discipline).where(course_disciplines: { course_id: @course.id })
        selected_date = params[:selected_date]&.to_date || Date.current
        @schedules_by_day = generate_schedules_by_day(selected_date)
        # Здесь еще всяких преподов, участников, материалы и прочее
    end

    def new
        @course = Course.new
    end

    # Создание курса (без добавления пользователей)
    def create
        @course = Course.new(course_params)

        if !(@course.start_date.present? && @course.end_date.present? && @course.start_date <= @course.end_date)
            redirect_to request.referer, alert: "Неверно указаны сроки проведения"
            return
        end
        Course.transaction do
            if @course.save
              # Привязываем текущего пользователя к курсу в роли модератора, если это возможно
              moderator = current_user.get_role_user('moderator')
              @course.role_users << moderator if moderator
      
              redirect_to moderator_course_path(@course), notice: "Курс создан"
            else
              # Если курс не сохраняется из-за других ошибок валидации
              render 'new', status: :unprocessable_entity
            end
        end
    rescue ActiveRecord::RecordInvalid
        # В случае возникновения исключения в транзакции
        redirect_to request.referer, alert: "Произошла ошибка"
    end


    def edit
    end

    def update
        if @course.update(course_params)
            redirect_to moderator_course_path(@course)
        else
            redirect_to request.referer
        end
    end

    def edit_teachers
        @teacher_role_users = RoleUser.joins(:role).where(roles: { name: 'teacher' })
    end

    # Добавление преподавателей на курс
    # TODO: нужно переделать, потому что преподы добавляются не на сам курс, а на дисциплину_на_курсе
    #       поэтому нужно сделать добавление на конкретную дисицплину
    def update_teachers
        other_users = RoleUser.joins(:role, :courses).where.
            not(roles: { name: 'teacher'}).where( courses: { id: params[:id] }).ids

        merged_ids = other_users
        if params[:course] && params[:course][:teacher_role_users].present?
            merged_ids = other_users | params[:course][:teacher_role_users].map(&:to_i)
        end

        @course.role_user_ids = merged_ids
        redirect_to moderator_course_path(@course)
    end

    def edit_students
        @student_role_users = RoleUser.joins(:role).where(roles: { name: 'student' })
    end

    # TODO: добавление сделать также, как добавление в группу
    # TODO: накинуть транзакцию
    def update_students
        # Получаем ID пользователей с ролями, отличными от 'student', связанных с курсом
        other_users = RoleUser.joins(:role, :courses).where.
            not(roles: { name: 'student'}).where( courses: { id: params[:id] }).ids
        
        merged_ids = other_users

        # Собираем ID студентов из параметров, если они предоставлены
        if params[:course] && params[:course][:student_role_users].present?
            # Объединяем ID студентов и нестудентов
            merged_ids = other_users | params[:course][:student_role_users].map(&:to_i)
        end

        @course.role_user_ids = merged_ids
        redirect_to moderator_course_path(@course)
    end

    def edit_disciplines
        @disciplines = Discipline.all
    end

    def update_disciplines
        params[:course][:discipline_ids].each do |discipline_id|
            discipline = Discipline.find(discipline_id)
            @course.course_disciplines.find_or_create_by(discipline: discipline)
        end
        redirect_to moderator_course_path(@course)
    end

    def destroy
        @course.destroy
        redirect_to moderator_courses_path
    end

    # TODO: реализовать возможность управление списком модераторов курса

    private
        def generate_schedules_by_day(selected_date)
            start_date = selected_date.beginning_of_month
            end_date = selected_date.end_of_month
            (start_date..end_date).map do |date|
            schedules = Schedule.joins("INNER JOIN course_disciplines ON course_disciplines.id=schedules.course_discipline_id
            INNER JOIN disciplines ON disciplines.id=course_disciplines.discipline_id")
                .where(course_disciplines: { course_id: @course.id })
                .where('DATE(schedules.start_time) = ?', date)
            puts schedules.inspect
            { date: date, schedules: schedules }
            end
        end
        def check_access_to_discipline
            @course = Course.find(params[:id])
            redirect_to root_path, alert: 'Доступ запрещен' unless @course.role_users.exists?(user_id: current_user.id, role_id: Role.find_by(name: 'moderator')&.id) || @is_admin
        end

        def course_params
            params.require(:course).permit(:name, :start_date, :end_date, :description, :teacher_role_users, :student_role_users, :discipline_ids)
        end
end

app/controllers/moderator/disciplines_controller.rb
class Moderator::DisciplinesController < ModeratorController
    before_action :check_access_to_discipline, only: [:show, :edit, :update, :destroy]
    respond_to :js, only: [:create]

    def index
      if current_user.has_role?('admin')
        @disciplines = Discipline.page(params[:page]).per(5)
      else
        @disciplines = Discipline.joins(role_users: :role)
                                  .where(role_users: { user_id: current_user.id, roles: { name: 'moderator' } })
                                  .page(params[:page]).per(5)
      end
    end

    def show
      @materials = @discipline.materials
    end

    def new
        @discipline = Discipline.new
        # По-хорошему нужно для добавления сразу дисциплин
        # @material = Material.new
    end

    def create
      @discipline = Discipline.new(discipline_params)
      if @discipline.save
        moderator = current_user.get_role_user('moderator')
        if !moderator.nil?
          @discipline.role_users << moderator
        end
        redirect_to moderator_disciplines_path, notice: 'Дисциплина успешно создана!'
      else
        # Не используется, но мб есть смысл здесь сразу делать запрос, а не в бд
        # @available_materials = Material.all
        redirect_to request.referer, alert: "Имя должно быть уникальным"
      end
    end
    
    def update_order
      Rails.logger.info params[:ordered_ids].inspect
      params[:ordered_ids].each_with_index do |id, index|
        Material.find(id).update(order: index)
      end
      # Ответ сервера (например, статус 200 OK)
    end
  

    def edit
      @discipline = Discipline.find(params[:id])
      @materials = @discipline.materials
    end

    def update
      if @discipline.update(discipline_params)
        redirect_to moderator_discipline_path(@discipline), notice: 'Дисциплина успешно обновлена!'
      else
        @available_materials = Material.all
        redirect_to request.referer, alert: "Имя должно быть уникальным"
      end
    end

    def destroy
      @discipline.materials.destroy_all
      @discipline.destroy
      redirect_to moderator_disciplines_path, notice: 'Дисциплина успешно удалена!'
    end

    def detach_material
      @discipline = Discipline.find(params[:id])
      @material = @discipline.materials.find(params[:material_id])
      @discipline.materials.destroy(@material)
    
      respond_to do |format|
        format.js
      end
    end


    private

      def check_access_to_discipline
        @discipline = Discipline.find(params[:id])
        redirect_to root_path, alert: 'Доступ запрещен' unless @discipline.role_users.exists?(user_id: current_user.id, role_id: Role.find_by(name: 'moderator')&.id) || @is_admin
      end
    
      def discipline_params
        params.require(:discipline).permit(:name, :description, material_ids: [])
      end
end

app/controllers/moderator/materials_controller.rb
class Moderator::MaterialsController < ModeratorController
    before_action :check_access_to_discipline, 
            only: [:show, :edit, :update, :destroy]

    # TODO: сделать еще в разделе модерирования подраздел с материалами для управления всеми материалами

    def new
        @material = @discipline.materials.build
        # @discipline = Discipline.find(params[:discipline_id])
    end

    def show
        @material = Material.find(params[:id])
        @material_access = MaterialAccess.find_or_initialize_by(material_id: @material.id)
    end

    private
        def check_access_to_discipline
            @discipline = Discipline.find(params[:discipline_id])
            redirect_to root_path, alert: 'Доступ запрещен' unless @discipline.role_users.exists?(user_id: current_user.id, role_id: Role.find_by(name: 'moderator')&.id) || @is_admin
        end

        def course_params
            params.require(:course).permit(:name, :start_date, :end_date, :description, :teacher_role_users, :student_role_users, :discipline_ids)
        end
end

app/controllers/moderator_controller.rb
class ModeratorController < ApplicationController
    before_action :access_check
  
    def access_check
        # Можно сразу достать эту запись roleUser для дальнейщего использования
        @is_admin = current_user&.has_role?('admin')
        redirect_to root_path, alert: 'Доступ запрещен.' unless @is_admin || current_user&.has_role?('moderator')
    end
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
    def get_role_user_by_role(role)
        RoleUser.joins(:role).find_by(users: { id: current_user.id }, roles: { name: role })
    end
end

app/helpers/moderator/courses_helper.rb
module Moderator::CoursesHelper
end

app/helpers/moderator/disciplines_helper.rb
module Moderator::DisciplinesHelper
end

app/helpers/moderator/materials_helper.rb
module Moderator::MaterialsHelper
end

app/helpers/moderator_helper.rb
module ModeratorHelper
end

app/views/moderator/disciplines/edit.html.erb
<%= render "moderator/shared/nav" %>
  
<div class="my-3 p-3 bg-body rounded shadow-sm">
  <div class="d-flex flex-wrap align-items-center pb-2 border-bottom">
    <h3 class=" pb-2 mb-0 col-12 col-lg-auto me-lg-auto">Редактирование</h3>
    <div class="text-end">
      <%= button_to 'Отмена', moderator_discipline_path(@discipline), :method => :get, type: "button", class: "btn btn-outline-secondary" %>
    </div>
  </div>

  <%= form_with(model: @discipline, url: moderator_discipline_path, local: true) do |f| %>
    <div class="form-floating">
      <%= f.text_field :name, class: "form-control", id: "floatingInput", placeholder: ""  %>
      <%= f.label "Название", for: "floatingInput", class: "form-label" %>
    </div>

    <%= render partial: 'moderator/materials/materials_list_edit', locals: { materials: @discipline.materials, discipline: @discipline} %>
    <%= link_to 'Добавить материал', 'javascript.void(0);', id: 'addMaterialLink', class: "btn btn-outline-secondary" %>

    <div>
      <%= f.submit 'Сохранить', class: "btn btn-primary w-100 py-2" %>
    </div>
  <% end %>
    <%= render partial: 'moderator/materials/new_modal', locals: { discipline: @discipline } %>
  </div>

app/views/moderator/disciplines/index.html.erb
<%= render "moderator/shared/nav" %>

<div class="my-3 p-3 bg-body rounded shadow-sm">
  <div class="d-flex flex-wrap align-items-center pb-2 border-bottom">
    <h3 class=" pb-2 mb-0 col-12 col-lg-auto me-lg-auto">Дисциплины</h3>
    <div class="text-end">
      <%= button_to '+ Создать', new_moderator_discipline_path, :method => :get, type: "button", class: "btn btn-outline-secondary" %>
    </div>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Название</th>
        <th scope="col">Материалы</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
    <% @disciplines.each do |discipline| %>
        <tr>
          <td><%= label_tag "#{discipline.name}" %></td>
          <td><%= label_tag "#{discipline.materials.length}" %></td>
          <td class="text-end">
            <div class="dropdown">
              <button class="btn btn-outline-secondary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                Действия
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to 'Редактировать', edit_moderator_discipline_path(discipline), class: "dropdown-item" %>
                <%= link_to 'Удалить', moderator_discipline_path(discipline), data: { "turbo-method": :delete, confirm: 'Are you sure?'}, class: "dropdown-item" %>
                <%= link_to 'Просмотр', moderator_discipline_path(discipline), class: "dropdown-item"%>
              </ul>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @disciplines %>
</div>

app/views/moderator/disciplines/new.html.erb
<%= render "moderator/shared/nav" %>

<div class="my-3 p-3 bg-body rounded shadow-sm">
  <div class="d-flex flex-wrap align-items-center pb-2 border-bottom">
    <h3 class=" pb-2 mb-0 col-12 col-lg-auto me-lg-auto">Создание дисциплины</h3>
    <div class="text-end">
      <%= button_to 'Отмена', moderator_disciplines_path, :method => :get, type: "button", class: "btn btn-outline-secondary" %>
    </div>
  </div>

  <%= form_with(model: @discipline, url: moderator_disciplines_path, local: true) do |f| %>
    <div class="form-floating">
      <%= f.text_field :name, class: "form-control", id: "floatingInput", placeholder: ""  %>
      <%= f.label "Название", for: "floatingInput", class: "form-label" %>
    </div>

    <div class="form-floating">
      <%= f.text_field :description, class: "form-control", id: "floatingInput", placeholder: ""  %>
      <%= f.label "Описание", for: "floatingInput", class: "form-label" %>
    </div>
    
    <%= f.submit 'Создать', class: "btn btn-primary w-100 py-2" %>
  <% end %>
</div>

app/views/moderator/disciplines/show.html.erb
<%= render "moderator/shared/nav" %>

<div class="my-3 p-3 bg-body rounded shadow-sm">
  <div class="d-flex flex-wrap align-items-center pb-2">
    <h3 class=" pb-2 mb-0 col-12 col-lg-auto me-lg-auto"><%= @discipline.name %></h3>
    <div class="text-end">
      <%= button_to 'Редактировать', edit_moderator_discipline_path(@discipline), :method => :get, type: "button", class: "btn btn-outline-secondary" %>
    </div>
  </div>
  <div class="lead my-2 pb-2 border-bottom">Описание: <%= @discipline.description %></div>
  <%= render partial: 'moderator/materials/materials_list', locals: { materials: @discipline.materials, discipline: @discipline } %>
</div>

<%= render partial: 'materials/new_modal', locals: { discipline: @discipline } %>